- hosts: docker
  become: yes
  roles:
    - docker
  tags: docker

- hosts: haproxy
  become: yes
  tasks:
    - apt_repository:
        repo: ppa:vbernat/haproxy-1.7

    - apt:
        name: haproxy
        update_cache: yes

    - service:
        name: haproxy
        enabled: no
        state: stopped
  tags: haproxy

- hosts: mesos
  become: yes
  roles:
    - zookeeper-mesos-marathon
    - { role: marathon-lb, tags: mlb }
  tags: mesos
