- hosts: vm1
  become: yes
  tasks:

    # -- 1
    - name: start new transactions-api
      command: >
        docker run
          -d
          -p 8083:8080
          --name transactions-api-new
          0x06065a/jpoint2017-transactions-api:0.0.3
      tags: p1


    # -- 2
    - name: wait for healthcheck
      shell: curl http://localhost:8083/health
      register: result
      until: result.stdout.find("UP") != -1
      retries: 10
      delay: 1
      tags: p2


    # -- 3
    - name: copy config with 2 apps
      copy:
        src: haproxy-2-apps.conf
        dest: /var/haproxy.conf
      tags: p2

    - name: restart haproxy
      shell: haproxy -D -f /var/haproxy.conf -p /var/haproxy.pid -sf `cat /var/haproxy.pid`
      tags: p2


    # -- 4
    - name: wait for app to spin
      pause:
        seconds: 2
      tags: p2


    # -- 5
    - name: copy config with new app
      copy:
        src: haproxy-new-app.conf
        dest: /var/haproxy.conf
      tags: p3

    - name: restart haproxy
      shell: haproxy -D -f /var/haproxy.conf -p /var/haproxy.pid -sf `cat /var/haproxy.pid`
      tags: p3


    # -- 6
    - name: stop old transactions-api
      command: docker rm -f transactions-api-old
      tags: p3
