- hosts: vm1
  become: yes
  tasks:

    - name: clean sandbox
      command: killall -9 haproxy
      ignore_errors: yes

    - name: clean containers
      command: docker rm -f names-api-old names-api-new
      ignore_errors: yes



    - name: deploy names-api
      docker_container:
        image: 0x06065a/jpoint2017-names-api:1
        name: names-api
        pull: yes
        ports:
          - "8080:8080"
      tags: names-api

    - name: deploy holywars-api
      docker_container:
        image: 0x06065a/jpoint2017-holywars-api:1
        name: holywars-api
        pull: yes
        ports:
          - "8081:8081"
        env:
          API_NAMES_URL: "http://{{ ansible_default_ipv4.address }}:8080/name"
      tags: holywars-api
