- hosts: docker
  become: yes
  roles:
    - docker
  tags: docker

#- hosts: mesos
  #become: yes
  #roles:
    #- zookeeper-mesos-marathon
    #- marathon-lb
  #tags: mesos

#- hosts: haproxy
  #become: yes
  #roles:
    #- haproxy
  #tags: haproxy
