- hosts: vm1
  tasks:
    - name: deploy names-api
      docker_container:
        image: 0x06065a/jpoint2017-names-api
        name: names-api
        pull: yes
        ports:
          - "8080:8080"
      tags: names-api
